# Generated by Django 4.1.6 on 2023-03-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meal',
            table='meals',
        ),
    ]
