# Generated by Django 4.1.6 on 2023-02-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_meal_created_at_meal_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
