# Generated by Django 4.1.6 on 2023-03-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_meal_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='orders_count',
            field=models.IntegerField(default=0),
        ),
    ]
