# Generated by Django 4.0.7 on 2023-03-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_delivery_name_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='name',
            field=models.CharField(default='Delivery', max_length=200),
        ),
    ]
